name: Warehouse Management Deployment

on:
  push:
    branches:
      - master

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Upload Frontend-Build
        uses: actions/upload-artifact@v4
        with:
          name: 'frontend-build'
          path: 'frontend/dist/*'

  build-backend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'    # oder 'zulu', je nach Bedarf
          cache: 'maven'

      - name: Download Frontend-Build
        uses: actions/download-artifact@v4
        with:
          name: 'frontend-build'
          path: 'backend/src/main/resources/static'

      - name: Build Backend mit Maven
        run: mvn -B package --file backend/pom.xml

      - name: Upload App.jar
        uses: actions/upload-artifact@v4
        with:
          name: 'backend-artifact'
          path: 'backend/target/app.jar'


  push-to-docker-hub:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Backend Artefakt
        uses: actions/download-artifact@v4
        with:
          name: 'backend-artifact'      # so hast du das Artefakt beim Build benannt
          path: 'backend/target/'       # Zielordner für die heruntergeladene app.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .                           # verweist auf dein Dockerfile
          push: true                           # damit das Image hochgeladen wird
          tags: ${{secrets.DOCKER_IMAGE_TAG}}  # z.B. "myuser/my-backend:latest"

  deploy:
    needs: push-to-docker-hub
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}

